const STORE={news:'90i_news',gallery:'90i_gallery',videos:'90i_videos',contacts:'90i_contacts',settings:'90i_settings',dark:'90i_dark_mode',session:'90i_admin_session'};
const cats=['राष्ट्रीय','बिहार','झारखंड','राजनीति','देश-दुनिया','मनोरंजन','खेल','व्यापार','शिक्षा','टेक्नोलॉजी','लाइफस्टाइल'];
const images=['photo-1504711434969-e33886168f5c','photo-1529107386315-e1a2ed48a620','photo-1521295121783-8a321d551ad2','photo-1540747913346-19e32dc3e97e','photo-1551288049-bebda4e38f71','photo-1500530855697-b586d89ba3ee','photo-1581091226825-a6a2a5aee158','photo-1434030216411-0b793f4b4173','photo-1485846234645-a62644f84728','photo-1541872705-1f73c6400ec9'];
const headlines=[
'नई नीति से गांवों तक तेज़ विकास की उम्मीद, सरकार ने जारी किया रोडमैप','बिहार में नई औद्योगिक परियोजनाओं से युवाओं के लिए खुलेंगे अवसर','झारखंड के आदिवासी इलाकों में शिक्षा अभियान को मिली नई रफ्तार','संसद में जनहित के मुद्दों पर लंबी बहस, कई अहम प्रस्ताव पेश','वैश्विक मंच पर भारत की मजबूत आवाज़, सहयोग के नए रास्ते खुले','नई फिल्म ने पहले सप्ताह में जीता दर्शकों का दिल','भारतीय खिलाड़ियों ने शानदार प्रदर्शन से रचा नया इतिहास','बाजार में मजबूती, छोटे कारोबारों के लिए राहत की खबर','बोर्ड परीक्षाओं के लिए नई गाइडलाइन जारी, छात्रों को मिलेगी सुविधा','स्वदेशी तकनीक से डिजिटल सेवाओं में आएगा बड़ा बदलाव','स्वस्थ जीवन के लिए छोटे शहरों में बढ़ी साइकिलिंग की लोकप्रियता',
'राज्यों के बीच जल प्रबंधन पर बनी साझा कार्ययोजना','पटना में आधुनिक सार्वजनिक परिवहन परियोजना का विस्तार','रांची में महिला उद्यमियों के लिए विशेष सहायता केंद्र शुरू','चुनावी सुधारों पर सभी दलों से व्यापक संवाद की तैयारी','पड़ोसी देशों के साथ व्यापार बढ़ाने पर नई सहमति','रंगमंच महोत्सव में युवा कलाकारों की दमदार प्रस्तुतियां','राष्ट्रीय खेलों में बिहार के खिलाड़ियों ने जीते कई पदक','नई कर व्यवस्था पर व्यापार संगठनों ने रखे सुझाव','सरकारी स्कूलों में डिजिटल पुस्तकालय अभियान शुरू','कृषि क्षेत्र में ड्रोन तकनीक से बदलेगी निगरानी व्यवस्था','पारंपरिक भोजन को आधुनिक अंदाज में पेश कर रहे युवा शेफ',
'ग्रामीण स्वास्थ्य केंद्रों में बढ़ेंगी जांच सुविधाएं','गया में पर्यटन विकास के लिए विरासत पथ तैयार','जमशेदपुर में हरित ऊर्जा परियोजना का सफल परीक्षण','युवा मतदाताओं के लिए देशव्यापी जागरूकता अभियान','अंतरराष्ट्रीय सम्मेलन में जलवायु न्याय पर भारत का जोर','ओटीटी पर क्षेत्रीय कहानियों की बढ़ती लोकप्रियता','महिला क्रिकेट टीम की रोमांचक जीत से प्रशंसकों में उत्साह','स्टार्टअप निवेश में छोटे शहरों की हिस्सेदारी बढ़ी'];
const excerpts=['नीतिगत फैसले का असर आम नागरिकों तक पहुंचाने के लिए समयबद्ध कार्ययोजना बनाई गई है।','स्थानीय भागीदारी, पारदर्शिता और जवाबदेही को नई पहल के केंद्र में रखा गया है।','विशेषज्ञों का मानना है कि इस बदलाव से आने वाले महीनों में ठोस परिणाम दिखाई देंगे।'];
const isoDay=(offset=0)=>{const d=new Date();d.setDate(d.getDate()-offset);return d.toISOString().slice(0,10)};
function defaultNews(){return headlines.map((title,i)=>({id:1001+i,title,image:`https://images.unsplash.com/${images[i%images.length]}?auto=format&fit=crop&w=1200&q=76`,author:i%4===0?'संपादकीय डेस्क':i%3===0?'अंजलि सिंह':'न्यूज़ ब्यूरो',category:cats[i%cats.length],date:isoDay(i<8?0:Math.floor(i/8)),time:`${String(9+i%10).padStart(2,'0')}:${i%2?'30':'00'}`,excerpt:excerpts[i%3],content:`${excerpts[i%3]} यह पहल व्यापक जनभागीदारी के साथ लागू की जा रही है। संबंधित विभागों ने स्पष्ट किया है कि हर चरण की नियमित समीक्षा होगी और प्रगति की जानकारी सार्वजनिक की जाएगी।\n\nक्षेत्र के लोगों ने इस निर्णय का स्वागत किया है। उनका कहना है कि बुनियादी सुविधाओं, रोजगार और शिक्षा पर एक साथ ध्यान देने से विकास अधिक संतुलित होगा। विशेषज्ञों ने स्थानीय जरूरतों के अनुसार योजनाओं में लचीलापन बनाए रखने की सलाह दी है।\n\nप्रशासन ने शिकायत और सुझाव के लिए विशेष व्यवस्था भी बनाई है। अगले चरण में जिलास्तर पर समीक्षा बैठकें होंगी, जहां नागरिक समूहों और विषय विशेषज्ञों की राय शामिल की जाएगी।`,tags:[cats[i%cats.length],'भारत','ताज़ा खबर'],featured:i<5,breaking:i<4,slug:`news-${1001+i}`}))}
function defaults(){if(!localStorage.getItem(STORE.news))localStorage.setItem(STORE.news,JSON.stringify(defaultNews()));if(!localStorage.getItem(STORE.gallery))localStorage.setItem(STORE.gallery,JSON.stringify(images.map((x,i)=>({id:i+1,title:headlines[i],category:cats[i%cats.length],image:`https://images.unsplash.com/${x}?auto=format&fit=crop&w=1200&q=78`}))));if(!localStorage.getItem(STORE.videos))localStorage.setItem(STORE.videos,JSON.stringify(['M7lc1UVf-VE','aqz-KE-bpKQ','ysz5S6PUM-U','ScMzIvxBSi4','jNQXAC9IVRw','dQw4w9WgXcQ','LXb3EKWsInQ','E7wJTI-1dvQ','9bZkp7q19f0','kJQP7kiw5Fk'].map((x,i)=>({id:i+1,title:headlines[i+10],category:cats[i%cats.length],youtube:x}))))}
const get=(key)=>JSON.parse(localStorage.getItem(key)||'[]');
const GH={cfg:'90i_github_config',token:'90i_github_token',dataPath:'data/90i-data.json'};
const ghConfig=()=>{try{return JSON.parse(localStorage.getItem(GH.cfg)||'{}')}catch{return {}}};
const saveLocal=(key,val)=>localStorage.setItem(key,JSON.stringify(val));
const save=(key,val)=>{saveLocal(key,val);queueCloudSave()};
let cloudSaveTimer;
function queueCloudSave(){clearTimeout(cloudSaveTimer);cloudSaveTimer=setTimeout(pushCloud,350)}
function repoInfo(){const c=ghConfig();if(c.owner&&c.repo)return c;const host=location.hostname;const path=location.pathname.split('/').filter(Boolean);if(host.endsWith('.github.io'))return {owner:host.split('.')[0],repo:path[0]||'' ,branch:'main'};return {owner:'',repo:'',branch:'main'}}
async function fetchCloud(){const c=repoInfo();if(!c.owner||!c.repo)return null;const branch=c.branch||'main',url=`https://raw.githubusercontent.com/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/${encodeURIComponent(branch)}/${GH.dataPath}`;const r=await fetch(url+`?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return null;return await r.json()}
async function hydrateCloud(){defaults();try{const data=await fetchCloud();if(!data||typeof data!=='object')return;for(const key of [STORE.news,STORE.gallery,STORE.videos,STORE.contacts,STORE.settings])if(Array.isArray(data[key]))saveLocal(key,data[key]);}catch(e){console.warn('GitHub cloud read failed',e)}}
function b64utf8(s){return btoa(unescape(encodeURIComponent(s)))}
async function pushCloud(){const c=repoInfo(),token=sessionStorage.getItem(GH.token);if(!c.owner||!c.repo||!token)return;const branch=c.branch||'main',api=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${GH.dataPath}`;const payload={};for(const key of [STORE.news,STORE.gallery,STORE.videos,STORE.contacts,STORE.settings])payload[key]=get(key);try{let sha='';const gr=await fetch(api+`?ref=${encodeURIComponent(branch)}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json'}});if(gr.ok)sha=(await gr.json()).sha||'';const body={message:'Update 90I News CMS data',content:b64utf8(JSON.stringify(payload,null,2)),branch,...(sha?{sha}:{})};const r=await fetch(api,{method:'PUT',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());toast('डेटा GitHub पर सुरक्षित हो गया।')}catch(e){console.error(e);toast('GitHub sync नहीं हुआ। Admin Settings में Token/Repo जाँचें।')}}
const cleanRichText=(html='')=>{const doc=new DOMParser().parseFromString(`<div>${html}</div>`,'text/html'),root=doc.body.firstElementChild;const allowed=new Set(['B','STRONG','I','EM','U','BR','P','DIV']);root.querySelectorAll('*').forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes)}else{[...el.attributes].forEach(a=>el.removeAttribute(a.name))}});return root.innerHTML;};
const richToText=(html='')=>{const d=document.createElement('div');d.innerHTML=html;return d.innerText||d.textContent||'';}

const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=(d)=>new Intl.DateTimeFormat('hi-IN',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'));
function header(){const page=document.body.dataset.page;document.body.insertAdjacentHTML('afterbegin',`<div class="progress" id="progress"></div><div class="topbar"><div class="container"><span id="today"></span><div class="top-links"><a href="epaper.html">ई-पेपर</a><a href="contact.html">संपर्क</a><span>● ◉ ▶</span></div></div></div><header class="masthead"><div class="container"><a href="index.html"><div class="logo">THE <b>90I</b> NEWS</div><div class="tagline">सच | सटीक | निर्भीक</div></a><div class="mast-actions"><button class="icon-btn" onclick="location.href='search.html'">⌕ <span class="label">खोजें</span></button><button class="icon-btn" id="theme">◐</button></div></div></header><nav class="main-nav"><div class="container nav-inner"><button class="icon-btn menu-btn" id="menu">☰</button><div class="nav-links" id="nav"><a href="index.html">होम</a>${cats.map(c=>`<a href="category.html?cat=${encodeURIComponent(c)}">${c}</a>`).join('')}<a href="gallery.html">फोटो</a><a href="video.html">वीडियो</a><a href="epaper.html">ई-पेपर</a></div></div></nav><div class="ticker"><div class="container"><div class="ticker-label">ब्रेकिंग</div><div class="ticker-track"><div class="ticker-items" id="ticker"></div></div></div></div>`);document.getElementById('today').textContent=new Intl.DateTimeFormat('hi-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(STORE.dark,document.body.classList.contains('dark')?'1':'0')};if(localStorage.getItem(STORE.dark)==='1')document.body.classList.add('dark');document.getElementById('ticker').innerHTML=get(STORE.news).filter(n=>n.breaking).map(n=>`<a href="article.html?slug=${encodeURIComponent(n.slug||`news-${n.id}`)}">${esc(n.title)}</a>`).join('');}
function footer(){document.body.insertAdjacentHTML('beforeend',`<footer class="site-footer"><div class="container"><div class="footer-grid"><div><div class="logo">THE <b>90I</b> NEWS</div><p>भारत की खबरें, जनता की आवाज़। विश्वसनीय और निर्भीक हिंदी पत्रकारिता का डिजिटल मंच।</p></div><div><h3>समाचार</h3><a href="category.html?cat=राष्ट्रीय">राष्ट्रीय</a><a href="category.html?cat=बिहार">बिहार</a><a href="category.html?cat=राजनीति">राजनीति</a><a href="category.html?cat=खेल">खेल</a></div><div><h3>विशेष</h3><a href="gallery.html">फोटो गैलरी</a><a href="video.html">वीडियो</a><a href="epaper.html">ई-पेपर</a><a href="admin.html">एडमिन</a></div><div><h3>कंपनी</h3><a href="about.html">हमारे बारे में</a><a href="contact.html">संपर्क</a><a href="privacy.html">गोपनीयता</a><a href="terms.html">नियम एवं शर्तें</a></div></div><div class="copyright">© ${new Date().getFullYear()} THE 90I NEWS. सर्वाधिकार सुरक्षित।</div></div></footer>`)}
const card=n=>`<article class="news-card"><a href="article.html?slug=${encodeURIComponent(n.slug||`news-${n.id}`)}"><img loading="lazy" src="${n.image}" alt="${esc(n.title)}"><div class="card-body"><span class="kicker">${esc(n.category)}</span><h3>${esc(n.title)}</h3><div class="meta">${fmt(n.date)} • ${esc(n.author)}</div><p>${esc(n.excerpt)}</p></div></a></article>`;
const side=n=>`<a class="side-feature" href="article.html?slug=${encodeURIComponent(n.slug||`news-${n.id}`)}"><img loading="lazy" src="${n.image}" alt=""><div><span class="kicker">${esc(n.category)}</span><h3>${esc(n.title)}</h3><span class="meta">${fmt(n.date)}</span></div></a>`;
function renderHome(){const news=get(STORE.news),lead=news.find(n=>n.featured)||news[0];const sections=['राष्ट्रीय','बिहार','झारखंड','राजनीति','खेल','व्यापार','टेक्नोलॉजी','शिक्षा','मनोरंजन','लाइफस्टाइल'];document.querySelector('main').innerHTML=`<div class="container page-shell"><div class="hero-grid"><a class="lead-card" href="article.html?slug=${encodeURIComponent(lead.slug||`news-${lead.id}`)}"><img src="${lead.image}" alt="${esc(lead.title)}"><div class="lead-overlay"><span class="kicker">मुख्य समाचार</span><h1>${esc(lead.title)}</h1><p>${esc(lead.excerpt)}</p></div></a><div class="panel card-body side-stack">${news.slice(1,5).map(side).join('')}</div></div></div><section class="section"><div class="container"><div class="section-title"><h2>ताज़ा खबरें</h2><a href="search.html">सभी देखें →</a></div><div class="news-grid">${news.slice(5,11).map(card).join('')}</div></div></section>${sections.map((c,i)=>`<section class="section"><div class="container"><div class="section-title"><h2>${c}</h2><a href="category.html?cat=${encodeURIComponent(c)}">और पढ़ें →</a></div><div class="news-grid">${news.filter(n=>n.category===c).slice(0,3).map(card).join('')}</div></div></section>${i===2?'<div class="container ad-strip"><div><strong>THE 90I NEWS ई-पेपर</strong><br>आज का पूरा अख़बार एक ही जगह पढ़ें</div><a class="btn btn-primary" href="epaper.html">अभी पढ़ें</a></div>':''}`).join('')}<section class="section"><div class="container"><div class="section-title"><h2>फोटो गैलरी</h2><a href="gallery.html">पूरी गैलरी →</a></div><div class="gallery-grid">${get(STORE.gallery).slice(0,4).map(g=>`<a class="gallery-item" href="gallery.html"><img loading="lazy" src="${g.image}" alt="${esc(g.title)}"><span>${esc(g.title)}</span></a>`).join('')}</div></div></section><section class="section"><div class="container newsletter"><div><h2>सुबह की प्रमुख खबरें सीधे आपके इनबॉक्स में</h2><p>स्पैम नहीं, सिर्फ जरूरी और विश्वसनीय समाचार।</p></div><form id="newsletter"><input type="email" required placeholder="ईमेल पता"><button class="btn btn-primary">सदस्य बनें</button></form></div></section>`;document.getElementById('newsletter').onsubmit=e=>{e.preventDefault();toast('न्यूज़लेटर सदस्यता सफल रही।');e.target.reset()}}
function renderCategory(){const q=new URLSearchParams(location.search),cat=q.get('cat')||'राष्ट्रीय',items=get(STORE.news).filter(n=>n.category===cat);document.title=`${cat} समाचार | THE 90I NEWS`;document.querySelector('main').innerHTML=`<div class="container page-shell"><div class="page-head"><span class="kicker">समाचार श्रेणी</span><h1 class="page-title">${esc(cat)}</h1></div><div class="news-grid">${items.length?items.map(card).join(''):'<div class="empty">इस श्रेणी में अभी कोई समाचार नहीं है।</div>'}</div></div>`}
function setSeo(n){const title=n.seoTitle||`${n.title} | THE 90I NEWS`,desc=n.seoDescription||n.excerpt||n.title,canonical=n.permalink||`${location.origin}/news/${encodeURIComponent(n.slug||`news-${n.id}`)}`;document.title=title;const set=(sel,attr,val)=>{let e=document.head.querySelector(sel);if(!e){e=document.createElement('meta');document.head.appendChild(e)}e.setAttribute(attr,val)};set('meta[name=description]','content',desc);set('meta[name=keywords]','content',n.seoKeywords||((n.tags||[]).join(', ')));set('meta[property="og:title"]','content',title);set('meta[property="og:description"]','content',desc);set('meta[property="og:image"]','content',n.image||'');let link=document.head.querySelector('link[rel=canonical]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;let ld=document.getElementById('news-jsonld');if(ld)ld.remove();ld=document.createElement('script');ld.id='news-jsonld';ld.type='application/ld+json';ld.textContent=JSON.stringify({'@context':'https://schema.org','@type':'NewsArticle','headline':n.title,'description':desc,'image':n.image?[n.image]:[],'datePublished':`${n.date}T${n.time||'00:00'}:00+05:30`,'author':{'@type':'Person','name':n.author||'THE 90I NEWS'},'mainEntityOfPage':canonical});document.head.appendChild(ld)}
function renderArticle(){const params=new URLSearchParams(location.search),slug=params.get('slug'),id=Number(params.get('id')),news=get(STORE.news),n=news.find(x=>slug?x.slug===slug:x.id===id)||news[0];if(!n){document.querySelector('main').innerHTML='<div class="container page-shell"><div class="empty">खबर उपलब्ध नहीं है।</div></div>';return}setSeo(n);const related=news.filter(x=>x.category===n.category&&x.id!==n.id).slice(0,3),body=cleanRichText(n.content||'');document.querySelector('main').innerHTML=`<div class="container page-shell article-layout"><article class="article-main"><span class="kicker">${esc(n.category)}</span><h1>${esc(n.title)}</h1><div class="meta">${fmt(n.date)} • ${esc(n.time||'')} • ${esc(n.author||'')}</div><img class="article-image" src="${n.image}" alt="${esc(n.title)}"><p class="notice">${esc(n.excerpt||'')}</p><div class="article-body">${body}</div><div class="tags">${(n.tags||[]).map(t=>`<span class="btn">#${esc(t)}</span>`).join('')}</div><div class="share-row"><button class="btn btn-primary" onclick="sharePage()">शेयर करें</button><button class="btn" onclick="print()">प्रिंट करें</button></div><div class="section-title"><h2>संबंधित खबरें</h2></div><div class="news-grid">${related.map(card).join('')}</div></article><aside><div class="sidebar-card"><h2>ताज़ा खबरें</h2>${news.slice(0,6).map(side).join('')}</div></aside></div>`;addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;document.getElementById('progress').style.width=h?`${scrollY/h*100}%`:'0%'})}

function renderSearch(){document.querySelector('main').innerHTML=`<div class="container page-shell"><div class="page-head"><span class="kicker">खोज</span><h1 class="page-title">समाचार खोजें</h1></div><div class="search-box"><input id="query" autofocus placeholder="शीर्षक, श्रेणी या विषय लिखें…"><button class="btn btn-primary">खोजें</button></div><p id="count"></p><div class="news-grid" id="results"></div></div>`;const input=document.getElementById('query'),results=document.getElementById('results'),count=document.getElementById('count');const run=()=>{const q=input.value.trim().toLowerCase(),items=get(STORE.news).filter(n=>[n.title,n.content,n.excerpt,n.category,...n.tags].join(' ').toLowerCase().includes(q));count.textContent=q?`${items.length} परिणाम मिले`:'सभी ताज़ा समाचार';results.innerHTML=(q?items:get(STORE.news).slice(0,9)).map(card).join('')||'<div class="empty">कोई परिणाम नहीं मिला। दूसरे शब्द से खोजें।</div>'};input.oninput=run;input.value=new URLSearchParams(location.search).get('q')||'';run()}
function renderGallery(){let all=get(STORE.gallery);document.querySelector('main').innerHTML=`<div class="container page-shell"><div class="page-head"><span class="kicker">दृश्य समाचार</span><h1 class="page-title">फोटो गैलरी</h1></div><div class="search-box"><select id="filter"><option>सभी</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="gallery-grid" id="gallery"></div></div>`;const draw=()=>{const f=document.getElementById('filter').value;document.getElementById('gallery').innerHTML=all.filter(g=>f==='सभी'||g.category===f).map(g=>`<div class="gallery-item" data-src="${g.image}"><img loading="lazy" src="${g.image}" alt="${esc(g.title)}"><span>${esc(g.title)}</span></div>`).join('');document.querySelectorAll('.gallery-item').forEach(x=>x.onclick=()=>{document.body.insertAdjacentHTML('beforeend',`<div class="modal" onclick="this.remove()"><img src="${x.dataset.src}" alt="फोटो"></div>`)})};document.getElementById('filter').onchange=draw;draw()}
function renderVideo(){const videos=get(STORE.videos);document.querySelector('main').innerHTML=`<div class="container page-shell"><div class="page-head"><span class="kicker">वीडियो</span><h1 class="page-title">वीडियो समाचार</h1></div><div class="news-grid">${videos.map(v=>`<article class="news-card"><iframe width="100%" height="220" loading="lazy" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(v.youtube)}" title="${esc(v.title)}" frameborder="0" allowfullscreen></iframe><div class="card-body"><span class="kicker">${esc(v.category)}</span><h3>${esc(v.title)}</h3></div></article>`).join('')}</div></div>`}
function renderEpaper(){const news=get(STORE.news),dates=[...new Set(news.map(n=>n.date))].sort().reverse();document.querySelector('main').innerHTML=`<div class="container page-shell"><div class="page-head"><span class="kicker">डिजिटल संस्करण</span><h1 class="page-title">ई-पेपर</h1></div><div class="epaper-actions search-box"><select id="paperDa
